#version: '3.8'

services:
  app:
    build: .
    container_name: it-backlog-manager
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    restart: unless-stopped
